### ISSUE TITLE
Minifying side-effect of CSS [attribute] Selector 

### ISSUE THREAD

**Issue by sambedingfield** [hexydec/htmldoc#4]
Hey, thanks for the amazing library!

I've been using an older version and just updated to `^1.0`.
A couple of notes...

1. I ran into trouble using `composer require hexydec/htmldoc`, and ended up needing `"minimum-stability": "dev",`. What's the best way to update to the latest stable version?
2. Since updating, I have a new side-effect when minifying a targeting CSS attribute with no value ([Vue's "v-cloak"](https://vuejs.org/v2/api/#v-cloak)). 

Before:
```
<style>
  *[v-cloak] {
    display: none;
  }
</style>
```
After:
```
<style>
  v-cloak {
    display: none;
  }
</style>
```
Thanks

**Comment by hexydec** [comment]
Hi,

Glad you are liking my work! Firstly this issue is a problem within the [CSSdoc project](https://github.com/hexydec/cssdoc), as the minifier for CSS and Javascript are in separate projects.

Have just tested your example in the latest code and it is working correctly, I fixed that issue a while ago.

The composer file currently specifies to pull the latest code for those dependencies as I work towards making official releases for those projects. So I suggest running `composer update` and making sure you have the latest code. Also it is worth running the latest HTMLdoc code too, although I will be making a new release shortly anyway.

Please let me know if you find any other issues.

**Comment by hexydec** [comment]
Have now release v1.2.0, suggest you update to that. Just make sure to `composer update` to get the latest dependencies.
